// ! Bu araç @Kraptor123 tarafından | @Cs-GizliKeyif için yazılmıştır.
package com.byayzen

import com.lagradost.cloudstream3.plugins.CloudstreamPlugin
import com.lagradost.cloudstream3.plugins.Plugin
import android.content.Context
import com.lagradost.cloudstream3.extractors.*
import com.lagradost.cloudstream3.extractors.FileMoonSx

@CloudstreamPlugin
class SextbPlugin: Plugin() {
    override fun load(context: Context) {
        registerMainAPI(Sextb())
        registerExtractorAPI(StreamTape())
        registerExtractorAPI(StreamTapeNet())
        registerExtractorAPI(StreamTapeXyz())
        registerExtractorAPI(Turboplayers())
        registerExtractorAPI(DoodStream())
        registerExtractorAPI(DoodDoply())
        registerExtractorAPI(DoodVideo())
        registerExtractorAPI(Ds2Play())
        registerExtractorAPI(d000d())
        registerExtractorAPI(VidHidePro())
        registerExtractorAPI(VidHidePro1())
        registerExtractorAPI(VidHidePro2())
        registerExtractorAPI(VidHidePro3())
        registerExtractorAPI(VidHidePro4())
        registerExtractorAPI(VidHidePro6())
        registerExtractorAPI(VidHidePro7())
        registerExtractorAPI(VidhideVIP())
        registerExtractorAPI(CloudWish())
        registerExtractorAPI(Dooood())
        registerExtractorAPI(Javlion())
        registerExtractorAPI(Dhcplay())
        registerExtractorAPI(Smoothpre())
        registerExtractorAPI(Dhtpre())
        registerExtractorAPI(Peytonepre())
        registerExtractorAPI(Movearnpre())
        registerExtractorAPI(Dintezuvio())
        registerExtractorAPI(Streamwish())
        registerExtractorAPI(Streamhihi())
        registerExtractorAPI(Javsw())
        registerExtractorAPI(swhoi())
        registerExtractorAPI(Javmoon())
        registerExtractorAPI(MixDropis())
        //   registerExtractorAPI(Javclan())
        registerExtractorAPI(Maxstream())
        registerExtractorAPI(Javggvideo())
        registerExtractorAPI(EmturbovidExtractor())
        registerExtractorAPI(FileMoonSx())
        registerExtractorAPI(DoodPmExtractor())
        registerExtractorAPI(FileMoonIn())
        registerExtractorAPI(VidNest())
        registerExtractorAPI(HgLink())
        registerExtractorAPI(RyderJet())
        registerExtractorAPI(UpnsOnline())
        registerExtractorAPI(EmbedSeek())
        registerExtractorAPI(VipSeekPlayer())
        registerExtractorAPI(EasyVidPlayer())
        registerExtractorAPI(VipEasyVidPlayer())
        registerExtractorAPI(MyCloudZ())
        registerExtractorAPI(VidStack())
        registerExtractorAPI(StbP2P())
        registerExtractorAPI(Playerupnone())
        registerExtractorAPI(Turtleviplay())
        registerExtractorAPI(Turboviplay())
        registerExtractorAPI(Vidguardto())
        registerExtractorAPI(MixDropAG())
        registerExtractorAPI(MixDropMy())
        registerExtractorAPI(FileMoon2())
        registerExtractorAPI(Bysedikamoum())
        registerExtractorAPI(Bysezoexe())
        registerExtractorAPI(Filemoonx08())
        registerExtractorAPI(Player4Me())
        registerExtractorAPI(Vip4me())
        registerExtractorAPI(RPMShare())
        registerExtractorAPI(Playmogo())
        registerExtractorAPI(Voe())
        registerExtractorAPI(Stape())
        registerExtractorAPI(StreamTAPE())
        registerExtractorAPI(ShaveTape())
        registerExtractorAPI(Watchadsontape())
        registerExtractorAPI(Lancewhoisdifficult())
        registerExtractorAPI(Javlesbians())
        registerExtractorAPI(LULUSTREAM())
        registerExtractorAPI(LULUVDO())
        registerExtractorAPI(LULUVDOO())
        registerExtractorAPI(LULUPVP())
        registerExtractorAPI(LULUDLC())
        registerExtractorAPI(LULU0())
        registerExtractorAPI(LULUX08())
    }
}